    //
    //
    // The sequence of triangle numbers is generated by adding the natural numbers.
    // So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
    // ten terms would be:
    //
    // 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
    //
    // Let us list the factors of the first seven triangle numbers:
    //
    //      1: 1
    //      3: 1,3
    //      6: 1,2,3,6
    //     10: 1,2,5,10
    //     15: 1,3,5,15
    //     21: 1,3,7,21
    //     28: 1,2,4,7,14,28
    //
    // We can see that 28 is the first triangle number to have over five divisors.
    //
    // What is the value of the first triangle number to have over five hundred
    // divisors?

    (function() {

        var divisorcount = function(num) {

            var sqrt = Math.sqrt(num);
            var sqrtint = Math.floor(sqrt);
            var count = 0;

            for (var d = 1; d <= sqrtint; d++)
                if (num % d == 0) count += 2;

            return sqrt == sqrtint ? count - 1 : count;

        }


        var triangledivisors = function(count) {

            var i = 2;
            var triangle = 1;

            while (divisorcount(triangle) < count)
                triangle += (i++);

            return triangle;

        }


        var start = new Date();
        var out = triangledivisors(500);
        var end = new Date();

        console.log(out, end.getTime() - start.getTime(), 'ms');
    })();
