

// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.

(function() {

    var fibsum = function(limit) {

        var a = 1;
        var b = 2;
        var sum = 0;

        while (b < limit) {

            if (b%2 == 0) sum += b;

            [a,b] = [b, a+b];


        }

        return sum;

    }

    var start = new Date();
    var out = fibsum(4e6);
    var end = new Date();

    console.log(out, end.getTime() - start.getTime(), 'ms');

})();
