#How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2<= b <= 100?

terms = []

for a in range(2,100+1):
    for b in range(2, 100+1):
        ab = a**b
        if not ab in terms:
            terms.append(ab)

print len(terms)